### ISSUE TITLE
erreur d'encodage

### ISSUE THREAD

**Issue by mentat51** [desbma/canalplus#4]
Bonjour.

J'adore "opération frisson" disponible sur le player de canal plus. Donc je télécharge votre programme, je lance : 
canalplus.exe -p "?frisson" test
dans l'invite de commande et j'obtiens : 
1. TEMPETE DE BOULETTES GEANTES - Sortie DVD (Frisson Break du 26/02/10)
   Traceback (most recent call last):
   File "C:\usr\bin\Python35\Scripts\canalplus-script.py", line 9, in <module>
     load_entry_point('canalplus==1.0.9', 'console_scripts', 'canalplus')()
   File "C:\usr\bin\Python35\lib\site-packages\canalplus-1.0.9-py3.5.egg\canalplus__init__.py", line 511, in cl_main
   File "C:\usr\bin\Python35\lib\site-packages\canalplus-1.0.9-py3.5.egg\canalplus__init__.py", line 409, in terminal_choice
   File "C:\usr\bin\Python35\lib\encodings\cp850.py", line 19, in encode
     return codecs.charmap_encode(input,self.errors,encoding_map)[0]
   UnicodeEncodeError: 'charmap' codec can't encode character '\x92' in position 22: character maps to <undefined>

Testé sous windows 10 / Python 3.5

**Comment by desbma** [comment]
Bonjour,

J'ai réussi à reproduire l'erreur sous Windows, mais pas sous Linux.
Le problème vient d'une des vidéos dont le nom a un caractère un peu atypique, que la console Windows ne sait pas afficher (car ne gérant pas l'UTF-8).

Solution : pour indiquer que Python peut ignorer silencieusement ces erreurs, définir la variable d'environnement `PYTHONIOENCODING` à `:ignore` 
- soit dans la console avant de lancer le script avec :
  `set PYTHONIOENCODING=:ignore`
- soit en définissant une variable d'environnement Windows (ce qui rend le changement permanent)
